services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d:ro
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: {}

