version: "3.8"

services:
  consul:
    image: consul
    ports: ["8500:8500"]
    environment:
      CONSUL_BIND_INTERFACE: eth0

  service1:
    image: service-discovery-demo_service1:0.0.1-SNAPSHOT
    ports: ["8080:8080"]
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul

  service2:
    image: service-discovery-demo_service2:0.0.1-SNAPSHOT
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
