version: "3.8"

services:
  consul:
    image: consul
    ports: ["8500:8500"]
    environment:
      CONSUL_BIND_INTERFACE: eth0

  service1:
    image: consul-demo-service1:0.0.1-SNAPSHOT
    ports: ["8080:8080"]
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul

  service2a:
    image: consul-demo-service2:0.0.1-SNAPSHOT
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_DISCOVERY_INSTANCEID: foo

  service2b:
    image: consul-demo-service2:0.0.1-SNAPSHOT
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_DISCOVERY_INSTANCEID: bar

  service2c:
    image: consul-demo-service2:0.0.1-SNAPSHOT
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_DISCOVERY_INSTANCEID: baz

