spring.application.name=observability-example-web
spring.security.user.password=pass

# management.endpoints.web.exposure.include=health, metrics, prometheus

# すべてのリクエストのトレースが送信されるようにする
# (デフォルトでは過負荷を避けるためリクエストの10%だけを送信するようになっている)
management.tracing.sampling.probability=1.0

management.observations.annotations.enabled=true

management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
