# 設定できる項目とデフォルト値は次のWebページを参照:
# https://resilience4j.readme.io/docs/circuitbreaker#create-and-configure-a-circuitbreaker
resilience4j.circuitbreaker:
  instances:
    demo1:
      sliding-window-type: count-based
    demo2:
      sliding-window-type: count-based
    demo3:
      sliding-window-type: count-based
