name: spring-boot-sandbox

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:

    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: liberica
        java-version: 21
        cache: maven
    - name: Build with Maven
      run: mvn -B -e -ntp test -DexcludedGroups=FailOnGitHub
      env:
        LOGGING_LEVEL_ROOT: WARN
        LOGGING_LEVEL_ORG_HIBERNATE_SQL: WARN
        LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL_BASICBINDER: WARN
        LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_JDBC_CORE_JDBCTEMPLATE: WARN
        LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_JDBC_DATASOURCE_DATASOURCETRANSACTIONMANAGER: WARN

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

