name: spring-boot-sandbox

on:
  push:
    paths:
    - '**/src/**'
    - '**/pom.xml'
    - 'pom.xml'
    - '.github/workflows/spring-boot-sandbox.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17
        cache: maven
    - name: Build with Maven
      run: mvn -B -e test
      env:
        logging_level_root: WARN
        logging_level_org_hibernate_SQL: WARN
        logging_level_org_hibernate_type_descriptor_sql_BasicBinder: WARN
        logging_level_org_springframework_jdbc_core_JdbcTemplate: WARN
        logging_level_org_springframework_jdbc_datasource_DataSourceTransactionManager: WARN
